### PR TITLE
tests: Use TestSlide for better mocking

### PR DESCRIPTION
**Pull request by get9**
Adds use of [https://github.com/facebookincubator/testslide](TestSlide) for better tests. Performs better and more clear mocking of various objects/modules.

### CODE REVIEW

**Comment by get9** [comment]
Unsure if the requirements.txt is right or not, feel free to reject if that needs to be more specific.

**Comment by malmond77** [comment]
@get9 This seems fine. I am concerned that the continuous-integration is now failing. Can you look to resolve this?

**Comment by get9** [comment]
soooo.... no idea what's up with the python3.4 tests. Seems like it dies trying to find test modules? Not sure why it would fail only for that particular version. Setting up a python3.4 local test on linux I can't repro. Any ideas?

**Comment by get9** [comment]
Finally figured out the issue - TestSlide doesn't support < 3.5 (without fixing some contextlib imports). So we can either put up a PR to make that work on 3.4, OR just drop support for 3.4 and make the min python 3 supported version be 3.5. @jaymzh, @davide125: Any preference?

**Comment by davide125** [comment]
So the reason we use 3.4 specifically is because it's available in EPEL with a full compendium of modules. The latest updates added 3.6 as well, so that's probably a better choice than 3.5, but it's still missing a lot of modules (including psutil). With that said, if fixing TestSlide to work with 3.4 is easy enough I'd rather do that instead.

**Comment by get9** [comment]
Just merged https://github.com/facebookincubator/TestSlide/pull/11. @fornellas will be cutting a release today, so I'll kick off a new CI run and see if it downloads the latest TestSlide and verify everything works.

**Comment by fornellas** [comment]
1.4.8 has the changes :-D

**Comment by davide125** [comment]
This needs a rebase now that #18 has been merged

**Comment by davide125** [comment]
CI is now failing with `NameError: name 'testslide' is not defined`

**Comment by get9** [comment]
Working on fixing up merges and such. A few remaining pyre errors left that I've raised with the pyre team.

**Pull request merged**
